name: Maschinenbau Sync
description: Sync blueprints using Ansible playbook
inputs:
  blueprint-repository:
    description: 'The name of the repository to fetch blueprints from.'
    required: true
    default: chr1st1ank/maschinenbau
  blueprints:
    description: 'The names of the blueprints to install (space separated).'
    required: true
  blueprint-vars:
    description: 'Extra variables to pass to the blueprint playbooks (space separated).'
    default: license=apache2
  pull-request-branch:
    description: 'Branch where the changes should be pushed to.'
    default: maschinenbau-sync
  base-branch:
    description: 'Branch where the changes should be pushed to.'
    default: main
  push:
    description: 'Whether to push the changes.'
    default: "true"
  github-token:
    description: "Github Token for pushing the changes"
    required: true
  pull-request-labels:
    description: 'Labels to apply to created pull requests.'
    default: "maschinenbau"
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Log Inputs
      env:
        BLUEPRINT_REPOSITORY: ${{ inputs.blueprint-repository }}
        BLUEPRINTS: ${{ inputs.blueprints }}
        BLUEPRINT_VARS: ${{ inputs.blueprint-vars }}
        TARGET_BRANCH: ${{ inputs.pull-request-branch }}
        PUSH: ${{ inputs.push }}
      shell: bash
      run: |
        echo "BLUEPRINT_REPOSITORY = $BLUEPRINT_REPOSITORY"
        echo "BLUEPRINTS = $BLUEPRINTS"
        echo "BLUEPRINT_VARS = $BLUEPRINT_VARS"
        echo "TARGET_BRANCH = $TARGET_BRANCH"
        echo "PUSH = $PUSH"

    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/setup-python@v4.3.1
      with:
        python-version: 3.9

    - name: Install Ansible
      shell: bash
      run: |
        pip3 install ansible-core
        ansible-galaxy collection install community.general

    - name: Fetch Blueprints
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.blueprint-repository }}
        path: .maschinenbau

    - name: Run Ansible playbook
      shell: bash
      run: |
        for blueprint in ${{ inputs.blueprints }}; 
        do
            ansible-playbook \
            --connection=local --inventory 127.0.0.1, \
            --extra-vars="${{ inputs.blueprint-vars }} workdir=$(pwd)" \
            .maschinenbau/blueprints/${blueprint}/install-playbook.yaml
        done

    - name: Delete blueprint folder
      shell: bash
      run: |
        rm -rf .maschinenbau
        find . | grep -v .git

#    - name: Commit Changes
#      env:
#        GIT_COMMITTER_EMAIL: bot@github.com
#        GIT_COMMITTER_NAME: "Maschinenbau Bot"
#        TARGET_BRANCH: "${{ inputs.pull-request-branch }}"
#      shell: bash
#      run: |
#        git config --global user.email "$GIT_COMMITTER_EMAIL"
#        git config --global user.name "$GIT_COMMITTER_NAME"
#        git checkout -b $TARGET_BRANCH
#        git add -A .
#        git commit -m "[Maschinenbau] Sync templates"
#
#    - name: Push Changes
#      if: ${{ inputs.push == 'true' }}
#      env:
#        TARGET_BRANCH: "${{ inputs.pull-request-branch }}"
#      shell: bash
#      run: |
#        git push --force --set-upstream origin $TARGET_BRANCH

    - name: Create Pull Request
      if: ${{ inputs.push == 'true' }}
      uses: peter-evans/create-pull-request@v5
      with:
        token: "{{ inputs.github-token }}"
        commit-message: "[Maschinenbau] Sync templates"
        committer: "Maschinenbau Bot <bot@github.com>"
        branch: "${{ inputs.pull-request-branch }}"
        base: "${{ inputs.base-branch }}"
        title: "[Maschinenbau] Sync templates"
        labels: "${{ inputs.pull-request-labels }}"
        body: |
          Applying blueprints from repository ${{ inputs.blueprint-repository }}.
          
          Blueprints: ${{ inputs.blueprints }}
          Blueprint variables: ${{ inputs.blueprint-vars }}
