- name: Install the blueprint "github-paperwork"
  hosts: all
  tasks:
    - name: Show Inputs
      vars:
        msg: |
          workdir: {{ workdir }}
          license: {{ license }}
      debug:
        msg: "{{ msg.split('\n') }}"

    - name: Roll out root folder templates
      template:
        src: "{{ item }}"
        dest: "{{ workdir }}/{{ item | basename }}"
      with_fileglob:
        - templates/*

    - name: Remove single ISSUE_TEMPLATE if it exists
      file:
        path: "{{ workdir }}/.github/ISSUE_TEMPLATE.md"
        state: absent

    - name: Create ISSUE_TEMPLATE folder
      file:
        path: "{{ workdir }}/.github/ISSUE_TEMPLATE"
        state: directory
      register: folder_output

    - name: Roll out ISSUE_TEMPLATEs
      template:
        src: "{{ item }}"
        dest: "{{ workdir }}/.github/ISSUE_TEMPLATE/{{ item | basename }}"
      with_fileglob:
        - templates/.github/ISSUE_TEMPLATE/*

    - name: Copy license
      copy:
        src: "templates/licenses/{{license}}.txt"
        dest: "{{ workdir }}/LICENSE"
      when: license is defined

    - name: Remove other license files
      file:
        path: "{{ workdir }}/LICENSE.rst"
        state: absent

    - name: Add license to pyproject.toml
      block:
        - name: Check if pyproject.toml file exists
          stat:
            path: "{{ workdir }}/pyproject.toml"
          register: pyproject_toml_file

        - name: Add license line to pyproject.toml
          ini_file:
            path: "{{ workdir }}/pyproject.toml"
            section: project
            option: license
            value: '{file = "LICENSE"}'
          when: pyproject_toml_file.stat.exists

      when: license is defined
