- name: Install the blueprint "github-paperwork"
  hosts: all
  tasks:
    - name: Debug
      debug:
        msg: "{{ playbook_dir }}: {{ (playbook_dir, '../../.workdir') | path_join | realpath }}"

    - name: Determine workdir
      set_fact:
        workdir: "{{ (playbook_dir, '../../.workdir') | path_join | realpath }}"

    - name: Show workdir
      debug:
        msg: "{{ workdir }}"

    - name: Roll out root folder templates
      template:
        src: "{{ item }}"
        dest: "{{ workdir }}/{{ item | basename }}"
      with_fileglob:
        - templates/*

    - name: Remove single ISSUE_TEMPLATE if it exists
      file:
        path: "{{ workdir }}/.github/ISSUE_TEMPLATE.md"
        state: absent

    - name: Create ISSUE_TEMPLATE folder
      file:
        path: "{{ workdir }}/.github/ISSUE_TEMPLATE"
        state: directory
      register: folder_output

    - name: Roll out ISSUE_TEMPLATEs
      template:
        src: "{{ item }}"
        dest: "{{ workdir }}/.github/ISSUE_TEMPLATE/{{ item | basename }}"
      with_fileglob:
        - templates/.github/ISSUE_TEMPLATE/*

    - name: Copy license
      copy:
        src: "templates/licenses/{{license}}.txt"
        dest: "{{ workdir }}/LICENSE"
      when: license is defined
