name: Maschinenbau Sync Workflow

on:
  push:
    branches:
      - main

jobs:
  maschinenbau-test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Maschinenbau Sync Action
      uses: ./
      with:
        blueprint-repository: chr1st1ank/maschinenbau
        blueprints: test-blueprint test-blueprint2
        target-branch: test
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push: "false"

    - name: Test Changes
      run: |
        git diff-tree --no-commit-id --name-only -r HEAD
        test $(git diff-tree --no-commit-id --name-only -r HEAD | grep test-file | wc -l) -eq 2 
